export const API_PREFIX: string = "https://imdb-api.com/en/API";
export const API_URLS: { [key: string]: string } = {
  popular_movies: `${API_PREFIX}/MostPopularMovies/${process.env.IMDB_API_KEY}`,
  popular_tvs: `${API_PREFIX}/MostPopularTVs/${process.env.IMDB_API_KEY}`,
  in_theatres: `${API_PREFIX}/InTheaters/${process.env.IMDB_API_KEY}`,
  coming_soon: `${API_PREFIX}/ComingSoon/${process.env.IMDB_API_KEY}`,
  get_details: `${API_PREFIX}/Title/${process.env.IMDB_API_KEY}/:titleId`,
};

export enum Filters {
  popular_movies = "Popular movies",
  popular_tvs = "Popular TVs",
  in_theatres = "In theaters",
  coming_soon = "Coming soon",
}

export const SomeTitles: string[] = [
  "tt3480822",
  "tt3554046",
  "tt9777666",
  "tt9701940",
  "tt6566576",
  "tt8368408",
  "tt9701942",
  "tt8332922",
  "tt5433138",
  "tt12801262",
  "tt6334354",
  "tt8847712",
  "tt11525644",
  "tt11003218",
  "tt3228774",
  "tt8772262",
  "tt7131622",
  "tt1321510",
  "tt0117705",
  "tt7601480",
  "tt10954652",
  "tt11083552",
  "tt8097030",
  "tt8244784",
  "tt8385148",
  "tt10327252",
  "tt13069986",
  "tt12877640",
  "tt7888964",
  "tt6932874",
  "tt10872600",
  "tt10696896",
  "tt4154796",
  "tt12528166",
  "tt11045422",
  "tt6644200",
  "tt3797512",
  "tt9844522",
  "tt9419884",
  "tt5109280",
  "tt10731768",
  "tt6723592",
  "tt10345590",
  "tt3758814",
  "tt1160419",
  "tt8404256",
  "tt6654210",
  "tt6264654",
  "tt6823148",
  "tt0068646",
  "tt2953050",
  "tt7069210",
  "tt11656220",
  "tt10648342",
  "tt11804152",
  "tt1697800",
  "tt9288692",
  "tt0870154",
  "tt0293429",
  "tt9373688",
  "tt10886166",
  "tt8110232",
  "tt12361974",
  "tt6217926",
  "tt0111161",
  "tt4154756",
  "tt0993840",
  "tt3501632",
  "tt9620292",
  "tt6513120",
  "tt5034838",
  "tt4824302",
  "tt10016180",
  "tt11121664",
  "tt0073195",
  "tt10954600",
  "tt1745960",
  "tt11027830",
  "tt4733624",
  "tt6856242",
  "tt12546872",
  "tt1086064",
  "tt10342730",
  "tt0241527",
  "tt7097896",
  "tt0110912",
  "tt9032400",
  "tt11245972",
  "tt3281548",
  "tt5886046",
  "tt1877830",
  "tt8231668",
  "tt9243804",
  "tt0116629",
  "tt1386697",
  "tt8695030",
  "tt5439812",
  "tt3774694",
  "tt4779326",
  "tt4555426",
];

export const TempTitleData = {
  id: "tt0110413",
  title: "Léon: The Professional",
  originalTitle: "Léon",
  fullTitle: "Léon: The Professional (1994)",
  type: "Movie",
  year: "1994",
  image:
    "https://imdb-api.com/images/original/MV5BODllNWE0MmEtYjUwZi00ZjY3LThmNmQtZjZlMjI2YTZjYmQ0XkEyXkFqcGdeQXVyNTc1NTQxODI@._V1_Ratio0.6791_AL_.jpg",
  releaseDate: "1994-09-14",
  runtimeMins: "110",
  runtimeStr: "1h 50mins",
  plot: "After her father, step-mother, step-sister and little brother are killed by her father's employers, the 12-year-old daughter of an abject drug dealer manages to take refuge in the apartment of a professional hitman who at her request teaches her the methods of his job so she can take her revenge on the corrupt DEA agent who ruined her life by killing her beloved brother.",
  plotLocal: "",
  plotLocalIsRtl: false,
  awards: "Top Rated Movies #31 | 6 wins & 15 nominations.",
  directors: "Luc Besson",
  directorList: [{ id: "nm0000108", name: "Luc Besson" }],
  writers: "Luc Besson",
  writerList: [{ id: "nm0000108", name: "Luc Besson" }],
  stars: "Jean Reno, Gary Oldman, Natalie Portman, Danny Aiello",
  starList: [
    { id: "nm0000606", name: "Jean Reno" },
    { id: "nm0000198", name: "Gary Oldman" },
    { id: "nm0000204", name: "Natalie Portman" },
    { id: "nm0000732", name: "Danny Aiello" },
  ],
  actorList: [
    {
      id: "nm0000606",
      image:
        "https://imdb-api.com/images/original/MV5BMTgzNjA1MjY2M15BMl5BanBnXkFtZTYwMjgzOTk0._V1_Ratio0.7273_AL_.jpg",
      name: "Jean Reno",
      asCharacter: "Leon",
    },
    {
      id: "nm0000198",
      image:
        "https://imdb-api.com/images/original/MV5BMTc3NTM4MzQ5MV5BMl5BanBnXkFtZTcwOTE4MDczNw@@._V1_Ratio0.7273_AL_.jpg",
      name: "Gary Oldman",
      asCharacter: "Stansfield",
    },
    {
      id: "nm0000204",
      image:
        "https://imdb-api.com/images/original/MV5BMTQ3ODE3Mjg1NV5BMl5BanBnXkFtZTcwNzA4ODcxNA@@._V1_Ratio0.7273_AL_.jpg",
      name: "Natalie Portman",
      asCharacter: "Mathilda",
    },
    {
      id: "nm0000732",
      image:
        "https://imdb-api.com/images/original/MV5BNTMxMjYzNzk5Nl5BMl5BanBnXkFtZTcwNzU4NDgwMw@@._V1_Ratio0.9545_AL_.jpg",
      name: "Danny Aiello",
      asCharacter: "Tony",
    },
    {
      id: "nm0032216",
      image:
        "https://imdb-api.com/images/original/MV5BMDVlNjcxM2ItNTU2NC00YzJkLWFlMzEtZGYwMTI0MmI5ZGE4XkEyXkFqcGdeQXVyNjkyNzAzNg@@._V1_Ratio0.7273_AL_.jpg",
      name: "Peter Appel",
      asCharacter: "Malky",
    },
    {
      id: "nm0089112",
      image:
        "https://imdb-api.com/images/original/MV5BNGU5YTdkODMtYjAxYS00NmM4LWI0MGEtZjZmNGMwYTA2Njg0XkEyXkFqcGdeQXVyNjUxMjc1OTM@._V1_Ratio2.3636_AL_.jpg",
      name: "Willi One Blood",
      asCharacter: "1st Stansfield Man (as Willie One Blood)",
    },
    {
      id: "nm0187199",
      image:
        "https://imdb-api.com/images/original/MV5BMTQ4MDMyODEyMF5BMl5BanBnXkFtZTgwNDI4OTQ1MjE@._V1_Ratio1.3182_AL_.jpg",
      name: "Don Creech",
      asCharacter: "2nd Stansfield Man",
    },
    {
      id: "nm0321798",
      image: "https://imdb-api.com/images/original/nopicture.jpg",
      name: "Keith A. Glascoe",
      asCharacter: "3rd Stansfield Man",
    },
    {
      id: "nm0779685",
      image: "https://imdb-api.com/images/original/nopicture.jpg",
      name: "Randolph Scott",
      asCharacter: "4th StansfieldMman",
    },
    {
      id: "nm0045937",
      image:
        "https://imdb-api.com/images/original/MV5BMTQxNTAxMjI3N15BMl5BanBnXkFtZTYwODY4MTg1._V1_Ratio0.7273_AL_.jpg",
      name: "Michael Badalucco",
      asCharacter: "Mathilda's Father",
    },
    {
      id: "nm0338746",
      image:
        "https://imdb-api.com/images/original/MV5BODczMTdmYTQtNjlmYS00MzgxLTk2ZWEtYmQ1ZWIzM2U0M2E1XkEyXkFqcGdeQXVyMTEwODg2MDY@._V1_Ratio1.3182_AL_.jpg",
      name: "Ellen Greene",
      asCharacter: "Mathilda's Mother",
    },
    {
      id: "nm0716408",
      image:
        "https://imdb-api.com/images/original/MV5BMTU3NzA1ODQ2OV5BMl5BanBnXkFtZTcwNDU5OTAzMQ@@._V1_Ratio0.7273_AL_.jpg",
      name: "Elizabeth Regen",
      asCharacter: "Mathilda's Sister",
    },
    {
      id: "nm0560593",
      image: "https://imdb-api.com/images/original/nopicture.jpg",
      name: "Carl J. Matusovich",
      asCharacter: "Mathilda's Brother",
    },
    {
      id: "nm0784262",
      image:
        "https://imdb-api.com/images/original/MV5BMTM1Njk4NTEyOV5BMl5BanBnXkFtZTYwNDI2Mzgy._V1_Ratio1.3636_AL_.jpg",
      name: "Frank Senger",
      asCharacter: "Fatman",
    },
    {
      id: "nm1707797",
      image:
        "https://imdb-api.com/images/original/MV5BZTk5MWQwYjctYmZmMy00MGE4LWIwN2ItMTA2ZjM2YjBkOGViXkEyXkFqcGdeQXVyNjUxMjc1OTM@._V1_Ratio1.6364_AL_.jpg",
      name: "Lucius Wyatt Cherokee",
      asCharacter: "Tonto (as Lucius Wyatt 'Cherokee')",
    },
  ],
  fullCast: null,
  genres: "Action, Crime, Drama, Thriller",
  genreList: [
    { key: "Action", value: "Action" },
    { key: "Crime", value: "Crime" },
    { key: "Drama", value: "Drama" },
    { key: "Thriller", value: "Thriller" },
  ],
  companies: "Gaumont, Les Films du Dauphin, Columbia Pictures",
  companyList: [
    { id: "co0172053", name: "Gaumont" },
    { id: "co0008826", name: "Les Films du Dauphin" },
    { id: "co0050868", name: "Columbia Pictures" },
  ],
  countries: "France, USA",
  countryList: [
    { key: "France", value: "France" },
    { key: "USA", value: "USA" },
  ],
  languages: "English, Italian, French",
  languageList: [
    { key: "English", value: "English" },
    { key: "Italian", value: "Italian" },
    { key: "French", value: "French" },
  ],
  contentRating: "R",
  imDbRating: "8.5",
  imDbRatingVotes: "1050598",
  metacriticRating: "64",
  ratings: null,
  wikipedia: null,
  posters: null,
  images: null,
  trailer: null,
  boxOffice: {
    budget: "FRF115,000,000 (estimated)",
    openingWeekendUSA: "$5,306,558, 20 November 1994",
    grossUSA: "$19,501,238",
    cumulativeWorldwideGross: "$19,552,639",
  },
  tagline:
    "A perfect assassin. An innocent girl. They have nothing left to lose except each other. He moves without sound. Kills without emotion. Disappears without trace. Only a 12 year old girl... knows his weakness.",
  keywords:
    "girl,hitman,teenage girl,older man young girl relationship,neo noir",
  keywordList: [
    "girl",
    "hitman",
    "teenage girl",
    "older man young girl relationship",
    "neo noir",
  ],
  similars: [
    {
      id: "tt0114369",
      title: "Se7en",
      fullTitle: "Se7en (1995)",
      year: "1995",
      image:
        "https://imdb-api.com/images/original/MV5BOTUwODM5MTctZjczMi00OTk4LTg3NWUtNmVhMTAzNTNjYjcyXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_Ratio0.6737_AL_.jpg",
      plot: "Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.",
      directors: "David Fincher",
      stars: "Morgan Freeman, Brad Pitt, Kevin Spacey",
      genres: "Crime, Drama, Mystery",
      imDbRating: "8.6",
    },
    {
      id: "tt0120689",
      title: "The Green Mile",
      fullTitle: "The Green Mile (1999)",
      year: "1999",
      image:
        "https://imdb-api.com/images/original/MV5BMTUxMzQyNjA5MF5BMl5BanBnXkFtZTYwOTU2NTY3._V1_Ratio0.6737_AL_.jpg",
      plot: "The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.",
      directors: "Frank Darabont",
      stars: "Tom Hanks, Michael Clarke Duncan, David Morse",
      genres: "Crime, Drama, Fantasy",
      imDbRating: "8.6",
    },
    {
      id: "tt0120586",
      title: "American History X",
      fullTitle: "American History X (1998)",
      year: "1998",
      image:
        "https://imdb-api.com/images/original/MV5BZTJhN2FkYWEtMGI0My00YWM4LWI2MjAtM2UwNjY4MTI2ZTQyXkEyXkFqcGdeQXVyNjc3MjQzNTI@._V1_Ratio0.6737_AL_.jpg",
      plot: "A former neo-nazi skinhead tries to prevent his younger brother from going down the same wrong path that he did.",
      directors: "Tony Kaye",
      stars: "Edward Norton, Edward Furlong, Beverly D'Angelo",
      genres: "Drama",
      imDbRating: "8.5",
    },
    {
      id: "tt0137523",
      title: "Fight Club",
      fullTitle: "Fight Club (1999)",
      year: "1999",
      image:
        "https://imdb-api.com/images/original/MV5BMmEzNTkxYjQtZTc0MC00YTVjLTg5ZTEtZWMwOWVlYzY0NWIwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_Ratio0.6737_AL_.jpg",
      plot: "A nameless first person narrator (Edward Norton) attends support groups in attempt to subdue his emotional state and relieve his insomniac state. When he meets Marla (Helena Bonham Carter),... See full summary »",
      directors: "David Fincher",
      stars: "Brad Pitt, Edward Norton, Meat Loaf",
      genres: "Drama",
      imDbRating: "8.8",
    },
    {
      id: "tt0102926",
      title: "The Silence of the Lambs",
      fullTitle: "The Silence of the Lambs (1991)",
      year: "1991",
      image:
        "https://imdb-api.com/images/original/MV5BNjNhZTk0ZmEtNjJhMi00YzFlLWE1MmEtYzM1M2ZmMGMwMTU4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_Ratio0.6737_AL_.jpg",
      plot: "A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.",
      directors: "Jonathan Demme",
      stars: "Jodie Foster, Anthony Hopkins, Lawrence A. Bonney",
      genres: "Crime, Drama, Thriller",
      imDbRating: "8.6",
    },
    {
      id: "tt0114814",
      title: "The Usual Suspects",
      fullTitle: "The Usual Suspects (1995)",
      year: "1995",
      image:
        "https://imdb-api.com/images/original/MV5BYTViNjMyNmUtNDFkNC00ZDRlLThmMDUtZDU2YWE4NGI2ZjVmXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_Ratio0.6737_AL_.jpg",
      plot: "A sole survivor tells of the twisty events leading up to a horrific gun battle on a boat, which began when five criminals met at a seemingly random police lineup.",
      directors: "Bryan Singer",
      stars: "Kevin Spacey, Gabriel Byrne, Chazz Palminteri",
      genres: "Crime, Mystery, Thriller",
      imDbRating: "8.5",
    },
    {
      id: "tt0110912",
      title: "Pulp Fiction",
      fullTitle: "Pulp Fiction (1994)",
      year: "1994",
      image:
        "https://imdb-api.com/images/original/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_Ratio0.6842_AL_.jpg",
      plot: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
      directors: "Quentin Tarantino",
      stars: "John Travolta, Uma Thurman, Samuel L. Jackson",
      genres: "Crime, Drama",
      imDbRating: "8.9",
    },
    {
      id: "tt0253474",
      title: "The Pianist",
      fullTitle: "The Pianist (2002)",
      year: "2002",
      image:
        "https://imdb-api.com/images/original/MV5BOWRiZDIxZjktMTA1NC00MDQ2LWEzMjUtMTliZmY3NjQ3ODJiXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_Ratio0.7263_AL_.jpg",
      plot: "A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto of World War II.",
      directors: "Roman Polanski",
      stars: "Adrien Brody, Thomas Kretschmann, Frank Finlay",
      genres: "Biography, Drama, Music",
      imDbRating: "8.5",
    },
    {
      id: "tt0109830",
      title: "Forrest Gump",
      fullTitle: "Forrest Gump (1994)",
      year: "1994",
      image:
        "https://imdb-api.com/images/original/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_Ratio0.6842_AL_.jpg",
      plot: "The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.",
      directors: "Robert Zemeckis",
      stars: "Tom Hanks, Robin Wright, Gary Sinise",
      genres: "Drama, Romance",
      imDbRating: "8.8",
    },
    {
      id: "tt0172495",
      title: "Gladiator",
      fullTitle: "Gladiator (2000)",
      year: "2000",
      image:
        "https://imdb-api.com/images/original/MV5BMDliMmNhNDEtODUyOS00MjNlLTgxODEtN2U3NzIxMGVkZTA1L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_Ratio0.6737_AL_.jpg",
      plot: "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
      directors: "Ridley Scott",
      stars: "Russell Crowe, Joaquin Phoenix, Connie Nielsen",
      genres: "Action, Adventure, Drama",
      imDbRating: "8.5",
    },
    {
      id: "tt0073486",
      title: "One Flew Over the Cuckoo's Nest",
      fullTitle: "One Flew Over the Cuckoo's Nest (1975)",
      year: "1975",
      image:
        "https://imdb-api.com/images/original/MV5BZjA0OWVhOTAtYWQxNi00YzNhLWI4ZjYtNjFjZTEyYjJlNDVlL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_Ratio0.6737_AL_.jpg",
      plot: "A criminal pleads insanity and is admitted to a mental institution, where he rebels against the oppressive nurse and rallies up the scared patients.",
      directors: "Milos Forman",
      stars: "Jack Nicholson, Louise Fletcher, Michael Berryman",
      genres: "Drama",
      imDbRating: "8.7",
    },
    {
      id: "tt0133093",
      title: "The Matrix",
      fullTitle: "The Matrix (1999)",
      year: "1999",
      image:
        "https://imdb-api.com/images/original/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_Ratio0.6737_AL_.jpg",
      plot: "When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.",
      directors: "Directors: Lana Wachowski, Lilly Wachowski",
      stars: "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss",
      genres: "Action, Sci-Fi",
      imDbRating: "8.7",
    },
  ],
  tvSeriesInfo: null,
  tvEpisodeInfo: null,
  errorMessage: "",
};
