import MovieDetails from "../models/movieDetails";

export const API_PREFIX: string = "https://imdb8.p.rapidapi.com";
export const API_URLS: { [key: string]: string } = {
  get_most_popular_movies: `${API_PREFIX}/title/get-most-popular-movies`,
  get_details: `${API_PREFIX}/title/get-overview-details`,
};
export const Titles: string[] = [
  "/title/tt9777666/",
  "/title/tt3480822/",
  "/title/tt6566576/",
  "/title/tt5433138/",
  "/title/tt11525644/",
  "/title/tt9701940/",
  "/title/tt12801262/",
  "/title/tt8332922/",
  "/title/tt6932874/",
  "/title/tt1321510/",
  "/title/tt8385148/",
  "/title/tt0116629/",
  "/title/tt6856242/",
  "/title/tt3228774/",
  "/title/tt10327252/",
  "/title/tt10230994/",
  "/title/tt11804152/",
  "/title/tt6334354/",
  "/title/tt8110232/",
  "/title/tt11027830/",
  "/title/tt3758814/",
  "/title/tt7888964/",
  "/title/tt7131622/",
  "/title/tt5109280/",
  "/title/tt10155932/",
  "/title/tt6733874/",
  "/title/tt9288692/",
  "/title/tt6217926/",
  "/title/tt8772262/",
  "/title/tt8079248/",
  "/title/tt3554046/",
  "/title/tt11083552/",
  "/title/tt2953050/",
  "/title/tt10954652/",
  "/title/tt9340860/",
  "/title/tt7601480/",
  "/title/tt9701942/",
  "/title/tt4824302/",
  "/title/tt6644200/",
  "/title/tt5439812/",
  "/title/tt7069210/",
  "/title/tt6723592/",
  "/title/tt4733624/",
  "/title/tt12528166/",
  "/title/tt6654210/",
  "/title/tt8231668/",
  "/title/tt10872600/",
  "/title/tt1086064/",
  "/title/tt0293429/",
  "/title/tt6246322/",
  "/title/tt0993840/",
  "/title/tt5034838/",
  "/title/tt0068646/",
  "/title/tt4154796/",
  "/title/tt10886166/",
  "/title/tt10696896/",
  "/title/tt0241527/",
  "/title/tt1745960/",
  "/title/tt10016180/",
  "/title/tt12361974/",
  "/title/tt6806448/",
  "/title/tt1160419/",
  "/title/tt0111161/",
  "/title/tt0803096/",
  "/title/tt9620292/",
  "/title/tt8041270/",
  "/title/tt3501632/",
  "/title/tt0110912/",
  "/title/tt10228134/",
  "/title/tt0232500/",
  "/title/tt4160708/",
  "/title/tt0108037/",
  "/title/tt1959563/",
  "/title/tt8244784/",
  "/title/tt0073195/",
  "/title/tt0118749/",
  "/title/tt9848626/",
  "/title/tt9770150/",
  "/title/tt14781176/",
  "/title/tt10288566/",
  "/title/tt8376234/",
  "/title/tt10648342/",
  "/title/tt1628841/",
  "/title/tt10272386/",
  "/title/tt6852526/",
  "/title/tt0089218/",
  "/title/tt0082186/",
  "/title/tt0103064/",
  "/title/tt9844522/",
  "/title/tt5562070/",
  "/title/tt2015381/",
  "/title/tt8404256/",
  "/title/tt0870154/",
  "/title/tt9243804/",
  "/title/tt6751668/",
  "/title/tt11245972/",
  "/title/tt0119174/",
  "/title/tt1877830/",
  "/title/tt7286456/",
  "/title/tt0134119/",
];
export const tempData: MovieDetails[] = [
  {
    id: "/title/tt9777666/",
    title: {
      "@type": "imdb.api.title.title",
      id: "/title/tt9777666/",
      image: {
        height: 12000,
        id: "/title/tt9777666/images/rm4098488833",
        url: "https://m.media-amazon.com/images/M/MV5BNTI2YTI0MWEtNGQ4OS00ODIzLWE1MWEtZGJiN2E3ZmM1OWI1XkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_.jpg",
        width: 8100,
      },
      runningTimeInMinutes: 138,
      title: "The Tomorrow War",
      titleType: "movie",
      year: 2021,
    },
    certificates: {
      US: [
        {
          certificate: "PG-13",
          certificateNumber: 53019,
          ratingReason:
            "Rated PG-13 for intense sequences of sci-fi violence and action, language and some suggestive references.",
          ratingsBody: "MPAA",
          country: "US",
        },
      ],
    },
    ratings: {
      canRate: true,
      rating: 6.6,
      ratingCount: 100303,
      topRank: 3202,
    },
    genres: ["Action", "Adventure", "Drama", "Sci-Fi", "Thriller"],
    releaseDate: "2021-07-02",
    plotOutline: {
      id: "/title/tt9777666/plot/po4366556",
      text: "A family man is drafted to fight in a future war where the fate of humanity relies on his ability to confront the past.",
    },
    plotSummary: {
      id: "/title/tt9777666/plot/ps5854133",
      text: "The world is stunned when a group of time travelers arrive from the year 2051 to deliver an urgent message: Thirty years in the future, mankind is losing a global war against a deadly alien species. The only hope for survival is for soldiers and civilians from the present to be transported to the future and join the fight. Among those recruited is high school teacher and family man Dan Forester (Chris Pratt). Determined to save the world for his young daughter, Dan teams up with a brilliant scientist (Yvonne Strahovski) and his estranged father (J.K. Simmons) in a desperate quest to rewrite the fate of the planet.",
    },
    imdbId: "tt9777666",
  },
  {
    id: "/title/tt3480822/",
    title: {
      "@type": "imdb.api.title.title",
      id: "/title/tt3480822/",
      image: {
        height: 1500,
        id: "/title/tt3480822/images/rm676068097",
        url: "https://m.media-amazon.com/images/M/MV5BNjRmNDI5MjMtMmFhZi00YzcwLWI4ZGItMGI2MjI0N2Q3YmIwXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg",
        width: 1013,
      },
      runningTimeInMinutes: 134,
      title: "Black Widow",
      titleType: "movie",
      year: 2021,
    },
    certificates: {
      US: [
        {
          certificate: "PG-13",
          certificateNumber: 52793,
          ratingReason:
            "Rated PG-13 for intense sequences of violence/action, some language and thematic material",
          ratingsBody: "MPAA",
          country: "US",
        },
      ],
    },
    ratings: {
      canRate: true,
      rating: 6.9,
      ratingCount: 104634,
      topRank: 2459,
    },
    genres: ["Action", "Adventure", "Sci-Fi"],
    releaseDate: "2021-07-09",
    plotOutline: {
      id: "/title/tt3480822/plot/po1954801",
      text: "Natasha Romanoff confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises.",
    },
    plotSummary: {
      author: "topmeasure",
      id: "/title/tt3480822/plot/ps5367193",
      text: 'In Marvel Studios\' action-packed spy thriller "Black Widow," Natasha Romanoff aka Black Widow confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises. Pursued by a force that will stop at nothing to bring her down, Natasha must deal with her history as a spy and the broken relationships left in her wake long before she became an Avenger.',
    },
    imdbId: "tt3480822",
  },
  {
    id: "/title/tt6566576/",
    title: {
      "@type": "imdb.api.title.title",
      id: "/title/tt6566576/",
      image: {
        height: 1500,
        id: "/title/tt6566576/images/rm776731393",
        url: "https://m.media-amazon.com/images/M/MV5BNzQzYjIyZDQtMjBhZS00MzU3LTk0MTQtNTVmMDI3ZWY0ZWU3XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg",
        width: 1013,
      },
      runningTimeInMinutes: 107,
      title: "Fear Street: Part One - 1994",
      titleType: "movie",
      year: 2021,
    },
    certificates: {
      US: [
        {
          certificate: "R",
          certificateNumber: 52388,
          ratingReason:
            "Rated R for strong bloody violence, drug content, language and some sexual content",
          ratingsBody: "MPAA",
          country: "US",
        },
      ],
    },
    ratings: {
      canRate: true,
      rating: 6.2,
      ratingCount: 32389,
      topRank: 3921,
    },
    genres: ["Drama", "Horror", "Mystery"],
    releaseDate: "2021-07-02",
    plotOutline: {
      author: "Netflix",
      id: "/title/tt6566576/plot/po6045447",
      text: "A circle of teenage friends accidentally encounter the ancient evil responsible for a series of brutal murders that have plagued their town for over 300 years. Welcome to Shadyside.",
    },
    imdbId: "tt6566576",
  },
  {
    id: "/title/tt5433138/",
    title: {
      "@type": "imdb.api.title.title",
      id: "/title/tt5433138/",
      image: {
        height: 2500,
        id: "/title/tt5433138/images/rm2544353793",
        url: "https://m.media-amazon.com/images/M/MV5BMjI0NmFkYzEtNzU2YS00NTg5LWIwYmMtNmQ1MTU0OGJjOTMxXkEyXkFqcGdeQXVyMjMxOTE0ODA@._V1_.jpg",
        width: 1579,
      },
      runningTimeInMinutes: 143,
      title: "F9: The Fast Saga",
      titleType: "movie",
      year: 2021,
    },
    certificates: {
      US: [
        {
          certificate: "PG-13",
          certificateNumber: 52936,
          ratingReason:
            "Rated PG-13 for sequences of violence and action, and language",
          ratingsBody: "MPAA",
          country: "US",
        },
      ],
    },
    ratings: {
      canRate: true,
      rating: 5.5,
      ratingCount: 33263,
      topRank: 4749,
    },
    genres: ["Action", "Adventure", "Crime", "Thriller"],
    releaseDate: "2021-06-25",
    plotOutline: {
      id: "/title/tt5433138/plot/po4966673",
      text: "Cipher enlists the help of Jakob, Dom's younger brother to take revenge on Dom and his team.",
    },
    imdbId: "tt5433138",
  },
  {
    id: "/title/tt11525644/",
    title: {
      "@type": "imdb.api.title.title",
      id: "/title/tt11525644/",
      image: {
        height: 6000,
        id: "/title/tt11525644/images/rm1239532801",
        url: "https://m.media-amazon.com/images/M/MV5BNWI2ZDQxZDQtZDMxZi00ZWFhLTg1OGYtYmFkMjRkMDc2NDNkXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg",
        width: 4050,
      },
      runningTimeInMinutes: 115,
      title: "No Sudden Move",
      titleType: "movie",
      year: 2021,
    },
    certificates: {
      US: [
        {
          certificate: "R",
          certificateNumber: 53098,
          ratingReason:
            "Rated R for language throughout, some violence and sexual references",
          ratingsBody: "MPAA",
          country: "US",
        },
      ],
    },
    ratings: {
      canRate: true,
      rating: 6.5,
      ratingCount: 11751,
    },
    genres: ["Crime", "Drama", "Mystery", "Thriller"],
    releaseDate: "2021-07-01",
    plotOutline: {
      id: "/title/tt11525644/plot/po4918976",
      text: "A group of criminals is brought together under mysterious circumstances and have to work together to uncover what's really going on when their simple job goes completely sideways.",
    },
    imdbId: "tt11525644",
  },
  {
    id: "/title/tt9701940/",
    title: {
      "@type": "imdb.api.title.title",
      id: "/title/tt9701940/",
      image: {
        height: 2222,
        id: "/title/tt9701940/images/rm1020786689",
        url: "https://m.media-amazon.com/images/M/MV5BOTQxMWNiZmYtOGUzMi00OGU5LTkzMjctYWY4ZmJkZjZiYWI5XkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_.jpg",
        width: 1500,
      },
      runningTimeInMinutes: 109,
      title: "Fear Street: Part Two - 1978",
      titleType: "movie",
      year: 2021,
    },
    certificates: {
      US: [
        {
          certificate: "R",
          certificateNumber: 52389,
          ratingReason:
            "Rated R for bloody horror violence, sexual content, nudity, drug use, and language throughout",
          ratingsBody: "MPAA",
          country: "US",
        },
      ],
    },
    ratings: {
      canRate: true,
      rating: 6.8,
      ratingCount: 19377,
    },
    genres: ["Drama", "Horror", "Mystery"],
    releaseDate: "2021-07-09",
    plotOutline: {
      author: "Netflix",
      id: "/title/tt9701940/plot/po4348111",
      text: "Shadyside, 1978. School's out for summer and the activities at Camp Nightwing are about to begin. But when another Shadysider is possessed with the urge to kill, the fun in the sun becomes a gruesome fight for survival.",
    },
    imdbId: "tt9701940",
  },
  {
    id: "/title/tt12801262/",
    title: {
      "@type": "imdb.api.title.title",
      id: "/title/tt12801262/",
      image: {
        height: 3000,
        id: "/title/tt12801262/images/rm3522740225",
        url: "https://m.media-amazon.com/images/M/MV5BZTQyNTU0MDktYTFkYi00ZjNhLWE2ODctMzBkM2U1ZTk3YTMzXkEyXkFqcGdeQXVyNTI4MzE4MDU@._V1_.jpg",
        width: 2025,
      },
      runningTimeInMinutes: 95,
      title: "Luca",
      titleType: "movie",
      year: 2021,
    },
    certificates: {
      US: [
        {
          certificate: "PG",
          certificateNumber: 53150,
          ratingReason:
            "Rated PG for rude humor, language, some thematic elements and brief violence",
          ratingsBody: "MPAA",
          country: "US",
        },
      ],
    },
    ratings: {
      canRate: true,
      rating: 7.5,
      ratingCount: 65498,
      topRank: 1210,
    },
    genres: ["Animation", "Adventure", "Comedy", "Family", "Fantasy"],
    releaseDate: "2021-06-18",
    plotOutline: {
      id: "/title/tt12801262/plot/po5240778",
      text: "On the Italian Riviera, an unlikely but strong friendship grows between a human being and a sea monster disguised as a human.",
    },
    plotSummary: {
      id: "/title/tt12801262/plot/ps5239772",
      text: "A young boy experiences an unforgettable seaside summer on the Italian Riviera filled with gelato, pasta and endless scooter rides. Luca shares these adventures with his newfound best friend, but all the fun is threatened by a deeply-held secret: he is a sea monster from another world just below the ocean's surface.",
    },
    imdbId: "tt12801262",
  },
  {
    id: "/title/tt8332922/",
    title: {
      "@type": "imdb.api.title.title",
      id: "/title/tt8332922/",
      image: {
        height: 1500,
        id: "/title/tt8332922/images/rm417579265",
        url: "https://m.media-amazon.com/images/M/MV5BMTE2ODU4NDEtNmRjNS00OTk1LTg4NmMtNTAzYzVlNzJmYjgzXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_.jpg",
        width: 1013,
      },
      runningTimeInMinutes: 97,
      title: "A Quiet Place Part II",
      titleType: "movie",
      year: 2020,
    },
    certificates: {
      US: [
        {
          certificate: "PG-13",
          certificateNumber: 52468,
          ratingReason:
            "Rated PG-13 for terror, violence and bloody/disturbing images.",
          ratingsBody: "MPAA",
          country: "US",
        },
      ],
    },
    ratings: {
      canRate: true,
      rating: 7.4,
      ratingCount: 94826,
      topRank: 1377,
    },
    genres: ["Drama", "Horror", "Sci-Fi", "Thriller"],
    releaseDate: "2021-05-28",
    plotOutline: {
      author: "Paramount Pictures",
      id: "/title/tt8332922/plot/po3882700",
      text: "Following the events at home, the Abbott family now face the terrors of the outside world. Forced to venture into the unknown, they realize the creatures that hunt by sound are not the only threats lurking beyond the sand path.",
    },
    plotSummary: {
      author: "Nick Riganas",
      id: "/title/tt8332922/plot/ps6104996",
      text: "With the newly acquired knowledge of the seemingly invulnerable creatures' weakness, grief-stricken Evelyn Abbott finds herself on her own, with two young teens, a defenceless newborn son, and with no place to hide. Now, 474 days after the all-out alien attack in A Quiet Place (2018), the Abbotts summon up every last ounce of courage to leave their now-burned-to-the-ground farm and embark on a peril-laden quest to find civilisation. With this in mind, determined to expand beyond the boundaries, the resilient survivors have no other choice but to venture into eerily quiet, uncharted hostile territory, hoping for a miracle. But, this time, the enemy is everywhere.",
    },
    imdbId: "tt8332922",
  },
  {
    id: "/title/tt6932874/",
    title: {
      "@type": "imdb.api.title.title",
      id: "/title/tt6932874/",
      image: {
        height: 1500,
        id: "/title/tt6932874/images/rm1134479105",
        url: "https://m.media-amazon.com/images/M/MV5BYWY1N2I5MGUtZTBmNS00MWZmLWEyNzAtZjliNzk0ZDVkYzI1XkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_.jpg",
        width: 947,
      },
      runningTimeInMinutes: 107,
      title: "The Boss Baby: Family Business",
      titleType: "movie",
      year: 2021,
    },
    certificates: {
      US: [
        {
          certificate: "PG",
          certificateNumber: 53046,
          ratingReason:
            "Rated PG for rude humor, mild language and some action",
          ratingsBody: "MPAA",
          country: "US",
        },
      ],
    },
    ratings: {
      canRate: true,
      rating: 6,
      ratingCount: 5827,
    },
    genres: ["Animation", "Adventure", "Comedy", "Family", "Fantasy"],
    releaseDate: "2021-07-02",
    plotOutline: {
      author: "Production",
      id: "/title/tt6932874/plot/po3383891",
      text: "The Templeton brothers have become adults and drifted away from each other, but a new boss baby with a cutting-edge approach is about to bring them together again - and inspire a new family business.",
    },
    imdbId: "tt6932874",
  },
  {
    id: "/title/tt1321510/",
    title: {
      "@type": "imdb.api.title.title",
      id: "/title/tt1321510/",
      image: {
        height: 3000,
        id: "/title/tt1321510/images/rm3639329025",
        url: "https://m.media-amazon.com/images/M/MV5BMzM1ZDY0YTktZTYzZi00MjZjLTllMDMtMmNlMmM5NmY4ZjllXkEyXkFqcGdeQXVyMTA1OTcyNDQ4._V1_.jpg",
        width: 2025,
      },
      runningTimeInMinutes: 143,
      title: "In the Heights",
      titleType: "movie",
      year: 2021,
    },
    certificates: {
      US: [
        {
          certificate: "PG-13",
          certificateNumber: 52857,
          ratingReason:
            "Rated PG-13 for some language and suggestive references",
          ratingsBody: "MPAA",
          country: "US",
        },
      ],
    },
    ratings: {
      canRate: true,
      rating: 7.5,
      ratingCount: 27463,
      topRank: 1391,
    },
    genres: ["Drama", "Music", "Musical", "Romance"],
    releaseDate: "2021-06-11",
    plotOutline: {
      id: "/title/tt1321510/plot/po1245049",
      text: "A film version of the Broadway musical in which Usnavi, a sympathetic New York bodega owner, saves every penny every day as he imagines and sings about a better life.",
    },
    plotSummary: {
      author: "Broadway.com",
      id: "/title/tt1321510/plot/ps0504930",
      text: "In the Heights centers on a variety of characters living in the neighborhood of Washington Heights, on the northern tip of Manhattan. At the center of the show is Usnavi, a bodega owner who looks after the aging Cuban lady next door, pines for the gorgeous girl working in the neighboring beauty salon and dreams of winning the lottery and escaping to the shores of his native Dominican Republic. Meanwhile, Nina, a childhood friend of Usnavi's, has returned to the neighborhood from her first year at college with surprising news for her parents, who have spent their life savings on building a better life for their daughter. Ultimately, Usnavi and the residents of the close-knit neighborhood get a dose of what it means to be home.",
    },
    imdbId: "tt1321510",
  },
];
