const LOCALES = {
  ie: "ie",
  es: "es",
  nl: "nl",
  gb: "gb",
  pl: "pl",
  lv: "lv",
  ch: "ch",
  dk: "dk",
  se: "se",
  no: "no",
  it: "it",
  md: "md",
  in: "in",
  cz: "cz",
  gr: "gr",
  ua: "ua",
  ca: "ca",
  pt: "pt",
  mx: "mx",
  ru: "ru",
  bg: "bg",
  cy: "cy",
  fi: "fi",
  be: "be",
  ae: "ae",
  at: "at",
  ee: "ee",
  th: "th",
  de: "de",
  az: "az",
  fr: "fr",
  br: "br",
  vn: "vn",
  sg: "sg",
  us: "us",
  jp: "jp",
  il: "il",
  hk: "hk",
  za: "za",
  pa: "pa",
  au: "au",
  ph: "ph",
  cl: "cl",
  ar: "ar",
  nz: "nz",
  co: "co",
  mk: "mk",
  rs: "rs",
  tn: "tn",
  ro: "ro",
  tr: "tr",
  ec: "ec",
  hu: "hu",
  id: "id",
  kr: "kr",
  lt: "lt",
  my: "my",
  pe: "pe",
  ve: "ve",
  is: "is",
};
const STREAMING_TYPE = {
  series: "series",
  movie: "movie",
};
const SERVICES = {
  apple: "apple",
  disney: "disney",
  hbo: "hbo",
  hulu: "hulu",
  mubi: "mubi",
  netflix: "netflix",
  paramount: "paramount",
  peacock: "peacock",
  prime: "prime",
  showtime: "showtime",
  stan: "stan",
  starz: "starz",
};

const LOCALE_SERVICE_DATA = {
  ie: [SERVICES.apple, SERVICES.mubi, SERVICES.netflix, SERVICES.prime],
  es: [
    SERVICES.apple,
    SERVICES.disney,
    SERVICES.mubi,
    SERVICES.netflix,
    SERVICES.prime,
  ],
  nl: [
    SERVICES.apple,
    SERVICES.disney,
    SERVICES.mubi,
    SERVICES.netflix,
    SERVICES.prime,
  ],
  gb: [
    SERVICES.apple,
    SERVICES.disney,
    SERVICES.mubi,
    SERVICES.netflix,
    SERVICES.prime,
  ],
  pl: [SERVICES.apple, SERVICES.mubi, SERVICES.netflix, SERVICES.prime],
  lv: [SERVICES.apple, SERVICES.mubi, SERVICES.netflix, SERVICES.prime],
  ch: [
    SERVICES.apple,
    SERVICES.disney,
    SERVICES.mubi,
    SERVICES.netflix,
    SERVICES.prime,
  ],
  dk: [
    SERVICES.apple,
    SERVICES.disney,
    SERVICES.mubi,
    SERVICES.netflix,
    SERVICES.prime,
  ],
  se: [
    SERVICES.apple,
    SERVICES.disney,
    SERVICES.mubi,
    SERVICES.netflix,
    SERVICES.prime,
  ],
  no: [
    SERVICES.apple,
    SERVICES.disney,
    SERVICES.mubi,
    SERVICES.netflix,
    SERVICES.prime,
  ],
  it: [
    SERVICES.apple,
    SERVICES.disney,
    SERVICES.mubi,
    SERVICES.netflix,
    SERVICES.prime,
  ],
  md: [SERVICES.apple, SERVICES.mubi, SERVICES.prime],
  in: [SERVICES.apple, SERVICES.mubi, SERVICES.netflix, SERVICES.prime],
  cz: [SERVICES.apple, SERVICES.netflix, SERVICES.prime],
  gr: [SERVICES.apple, SERVICES.mubi, SERVICES.netflix, SERVICES.prime],
  ua: [SERVICES.apple, SERVICES.mubi, SERVICES.prime],
  ca: [
    SERVICES.apple,
    SERVICES.disney,
    SERVICES.mubi,
    SERVICES.netflix,
    SERVICES.prime,
  ],
  pt: [
    SERVICES.apple,
    SERVICES.disney,
    SERVICES.mubi,
    SERVICES.netflix,
    SERVICES.prime,
  ],
  mx: [
    SERVICES.apple,
    SERVICES.disney,
    SERVICES.mubi,
    SERVICES.netflix,
    SERVICES.prime,
  ],
  ru: [SERVICES.apple, SERVICES.mubi, SERVICES.netflix, SERVICES.prime],
  bg: [SERVICES.apple, SERVICES.mubi, SERVICES.prime],
  cy: [SERVICES.apple, SERVICES.mubi, SERVICES.prime],
  fi: [
    SERVICES.apple,
    SERVICES.disney,
    SERVICES.mubi,
    SERVICES.netflix,
    SERVICES.prime,
  ],
  be: [
    SERVICES.apple,
    SERVICES.disney,
    SERVICES.mubi,
    SERVICES.netflix,
    SERVICES.prime,
  ],
  ae: [SERVICES.apple, SERVICES.mubi, SERVICES.prime],
  at: [
    SERVICES.apple,
    SERVICES.disney,
    SERVICES.mubi,
    SERVICES.netflix,
    SERVICES.prime,
  ],
  ee: [SERVICES.apple, SERVICES.mubi, SERVICES.netflix, SERVICES.prime],
  th: [SERVICES.apple, SERVICES.mubi, SERVICES.netflix, SERVICES.prime],
  de: [
    SERVICES.apple,
    SERVICES.disney,
    SERVICES.mubi,
    SERVICES.netflix,
    SERVICES.prime,
  ],
  az: [SERVICES.apple, SERVICES.mubi, SERVICES.prime],
  fr: [
    SERVICES.apple,
    SERVICES.disney,
    SERVICES.mubi,
    SERVICES.netflix,
    SERVICES.prime,
  ],
  br: [
    SERVICES.apple,
    SERVICES.disney,
    SERVICES.mubi,
    SERVICES.netflix,
    SERVICES.prime,
  ],
  vn: [SERVICES.apple, SERVICES.mubi, SERVICES.prime],
  sg: [SERVICES.apple, SERVICES.mubi, SERVICES.netflix, SERVICES.prime],
  us: [
    SERVICES.apple,
    SERVICES.disney,
    SERVICES.hbo,
    SERVICES.hulu,
    SERVICES.mubi,
    SERVICES.netflix,
    SERVICES.paramount,
    SERVICES.peacock,
    SERVICES.prime,
    SERVICES.showtime,
    SERVICES.starz,
  ],
  jp: [SERVICES.apple, SERVICES.mubi, SERVICES.netflix, SERVICES.prime],
  il: [SERVICES.apple, SERVICES.mubi, SERVICES.prime],
  hk: [SERVICES.apple, SERVICES.mubi, SERVICES.prime],
  za: [SERVICES.apple, SERVICES.mubi, SERVICES.netflix, SERVICES.prime],
  pa: [SERVICES.apple, SERVICES.mubi, SERVICES.prime],
  au: [
    SERVICES.apple,
    SERVICES.disney,
    SERVICES.mubi,
    SERVICES.netflix,
    SERVICES.prime,
    SERVICES.stan,
  ],
  ph: [SERVICES.apple, SERVICES.mubi, SERVICES.netflix, SERVICES.prime],
  cl: [
    SERVICES.apple,
    SERVICES.disney,
    SERVICES.mubi,
    SERVICES.netflix,
    SERVICES.prime,
  ],
  ar: [
    SERVICES.apple,
    SERVICES.disney,
    SERVICES.mubi,
    SERVICES.netflix,
    SERVICES.prime,
  ],
  nz: [
    SERVICES.apple,
    SERVICES.disney,
    SERVICES.mubi,
    SERVICES.netflix,
    SERVICES.prime,
  ],
  co: [SERVICES.disney, SERVICES.netflix],
  mk: [SERVICES.mubi, SERVICES.prime],
  rs: [SERVICES.mubi, SERVICES.prime],
  tn: [SERVICES.mubi, SERVICES.prime],
  ro: [SERVICES.mubi, SERVICES.netflix, SERVICES.prime],
  tr: [SERVICES.mubi, SERVICES.netflix, SERVICES.prime],
  ec: [SERVICES.netflix],
  hu: [SERVICES.netflix],
  id: [SERVICES.netflix],
  kr: [SERVICES.netflix],
  lt: [SERVICES.netflix],
  my: [SERVICES.netflix],
  pe: [SERVICES.netflix],
  ve: [SERVICES.netflix],
  is: [SERVICES.prime],
};

module.exports = {
  LOCALES,
  LOCALE_SERVICE_DATA,
  SERVICES,
  STREAMING_TYPE,
};
